#
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
"on":
  pull_request:
  push:
    branches:
      - "main"
  schedule:
    - cron: "10 2 * * 0"

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAGS: >-
    ${{ github.ref_name }}
    ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Dump env
        run: echo "$TAGS"

      - name: Dump context
        run: echo "${{ env.TAGS }}"

      - name: Add the latest tag
        run: |
          echo "TAGS=${{ env.TAGS }} latest" >> $GITHUB_ENV
        if: ${{ github.ref_name == 'main' }}

      - name: Dump env
        run: echo "$TAGS"

      - name: Dump context
        run: echo "${{ env.TAGS }}"

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4.6.0
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          containerfiles: |
            ./Containerfile
          build-args: |
            some_arg=some_value
          # tags: ${{ steps.meta.outputs.tags }}
          tags: >-
            ${{ github.ref_name }}
            ${{ github.sha }}
          # labels: ${{ steps.meta.outputs.labels }}

      - name: Push to ghcr.io
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          # tags: ${{ steps.meta.outputs.tags }}
          # tags: >
          #   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          # ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          tags: >-
            ${{ github.ref_name }}
            ${{ github.sha }}
